# Listar Usuários
GET http://localhost:8080/api/user
###


# Detalhes do usuário
GET http://localhost:8080/api/user/1
###

# Apagar usuário
DELETE http://localhost:8080/api/user/1
Authorization: Basic admin@fiap.com.br administrador
###

# Cadastrar usuário
POST http://localhost:8080/api/user
Content-Type: application/json
Authorization: Basic admin@fiap.com.br administrador

{
    "name":"Professor João, lindão!",
    "email": "joao@fiap.com.br",
    "password": "123"
}
###

# Alterar usuário

PUT http://localhost:8080/api/user/3
Content-Type: application/json
Authorization: Basic admin@fiap.com.br administrador

{
    "name":"Jonathan UPDATE",
    "email": "jonathan@fiap.com.br"
}
###


# Grupo
GET http://localhost:8080/grupo
###