# Listar Usuários
GET https://checkpoint-spring.herokuapp.com/api/user
###


# Detalhes do usuário
GET https://checkpoint-spring.herokuapp.com/api/user/1
###

# Apagar usuário
DELETE https://checkpoint-spring.herokuapp.com/api/user/1
Authorization: Basic admin@fiap.com.br administrador
###

# Cadastrar usuário
POST https://checkpoint-spring.herokuapp.com/api/user
Content-Type: application/json
Authorization: Basic admin@fiap.com.br administrador

{
    "name":"Professor João, lindão!",
    "email": "joao@fiap.com.br",
    "password": "123"
}
###

# Alterar usuário

PUT https://checkpoint-spring.herokuapp.com/api/user/3
Content-Type: application/json
Authorization: Basic admin@fiap.com.br administrador

{
    "name":"Jonathan UPDATE",
    "email": "jonathan@fiap.com.br"
}
###


# Grupo
GET https://checkpoint-spring.herokuapp.com/grupo
###